"use strict";
let myName = document.getElementById('name');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let addrs = document.getElementById('addrs');
let pass1 = document.getElementById('pass1');
let deg1 = document.getElementById('deg1');
let uni1 = document.getElementById('uni1');
let pass2 = document.getElementById('pass2');
let deg2 = document.getElementById('deg2');
let uni2 = document.getElementById('uni2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let lan1 = document.getElementById('lan1');
let lan2 = document.getElementById('lan2');
let styear = document.getElementById('styear');
let edyear = document.getElementById('edyear');
let company = document.getElementById('company');
let comloca = document.getElementById('comloca');
let jbtle = document.getElementById('jbtle');
let achi1 = document.getElementById('achi1');
let achi2 = document.getElementById('achi2');
let achi3 = document.getElementById('achi3');
let pic = document.getElementById('pic');
let subbtn = document.getElementById('subbtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem("name", myName.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("addrs", addrs.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg1", deg1.value);
    localStorage.setItem("uni1", uni1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("uni2", uni2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("lan1", lan1.value);
    localStorage.setItem("lan2", lan2.value);
    localStorage.setItem("styear", styear.value);
    localStorage.setItem("edyear", edyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("comloca", comloca.value);
    localStorage.setItem("jbtle", jbtle.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem("profile_pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./Resume_1/resume.html";
});
